### ISSUE TITLE
Image import is broken

### ISSUE THREAD

**Issue by benwr** [benwr/ankdown#7]
Somehow we're now creating invalid apkgs when there are images. One problem is the relative paths change, but there's some deeper problem, because even when that's fixed we produce invalid archives.

**Comment by benwr** [comment]
Fixed

**Comment by xhw1** [comment]
Hi, I just tested adding image but failed. Is this fixed in the current pip installed version?  I'm using version 0.5.2

**Comment by benwr** [comment]
Can you give more details about the failure? (yes, this should be fixed in the current pip version)

**Comment by LuccaHellriegel** [comment]
I can confirm, that the image import does not seem to work. 
I am using the following markdown with the picture in the same folder as the md-file:

> ![alt text](./test.bmp) # shows the picture in my editor (vscode)
> 
> Expected Value of \(f(x)\)
> 
> %
> 
> \[\mathbb{E}[f(x)] = \sum_x p(x)f(x)\]
> 
> %
> 
> math, probability
> 
> ---


When looking at the HTML of the first page I see:


> <p><img src=".%test.bmp"></p>
> 
> <p>Expected Value of \(f(x)\)</p>
> 

Replacing the relative path does not seem to change anything.
Is there maybe a minimum working example with a picture?

**Comment by benwr** [comment]
@LuccaHellriegel Weirdly, this seems to happen to me when I _first_ import the package, but then if I restart Anki the image shows up properly. Can you confirm that this doesn't happen for you? It's a pretty annoying workaround, but I'm not sufficiently aware of Anki / genanki's internals to fix the problem.

**Comment by benwr** [comment]
this might be related to https://github.com/kerrickstaley/genanki/issues/17

**Comment by LuccaHellriegel** [comment]
@benwr After restarting Anki, the image shows up, thanks. If I update the card, I also have to restart Anki. But thats not a big deal, but might deserve a mention somewhere in the readme. Anyway, thanks for your help.

**Comment by jay-pee** [comment]
When putting images in subfolders an error occurs:

```
Traceback (most recent call last):
  File "c:\Users\Philip\Documents\GitHub\ankdown\ankdown\ankdown.py", line 389, in main
    cards_to_apkg(card_iterator, pkg_arg)
  File "c:\Users\Philip\Documents\GitHub\ankdown\ankdown\ankdown.py", line 343, in cards_to_apkg
    copyfile(abspath, newpath) # This is inefficient but definitely works on all platforms.
  File "C:\Python36\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'assets/images/philly-magic-garden.jpg'
```

Maybe we have to create the folder before putting the image there with `copyfile(abspath, newpath)`.
Or change the `newpath` variable.
